name: Export And Publish Interfaces And Contracts - Canary

on: workflow_dispatch

jobs:
  export:
    name: Generate Interfaces And Contracts - Canary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        export_type: ['interfaces', 'contracts']

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build project and generate out directory
        run: yarn build

      - name: Update version
        run: yarn version --new-version "0.0.0-${GITHUB_SHA::8}" --no-git-tag-version

      - name: Export Solidity - ${{ matrix.export_type }}
        uses: defi-wonderland/solidity-exporter-action@v1
        with:
          package_name: '@defi-wonderland/xkeeper'
          out: 'out'
          interfaces: 'solidity/interfaces'
          contracts: 'solidity/contracts'
          export_type: '${{ matrix.export_type }}'

      - name: Publish
        run: cd export/@defi-wonderland/xkeeper-${{ matrix.export_type }} && npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}